---

# Essential softwares
- name: Install from apt
  become: yes
  become_method: sudo
  apt:
    state: latest
    update_cache: yes
    autoclean: yes
    name: 
      - "curl"
      - "git"
      - "vim"
      - "htop"
      - "cockpit"
